apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cart-service
  labels:
    release: monitoring
spec:
  endpoints:
    - port: http
      path: /metrics
      interval: 5s
  selector:
    matchLabels:
      app: cart-service
