#naming the first stage as 'deps'
FROM node:20-alpine AS deps 
WORKDIR /app
COPY package*.json .
RUN npm install --omit=dev

FROM node:20-alpine
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY package*.json server.js ./
EXPOSE 8080
CMD ["node", "server.js"]